# Generated by Django 5.2.10 on 2026-02-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langedu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_responses', to='langedu_app.textquestion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
